### ISSUE TITLE
New Listener messages not showing up

### ISSUE THREAD

**Issue by richeyrobert** [richeyllc/radiotext#1]
When a new listener texts a competition keyword with the improper case, they are not acknowledged. (Their message doesn't show up in the conversations pane)

Only when the proper case was texted were they acknowledged and their messages available on the conversations screen.

**Comment by ghost** [comment]
Wasn't this fixed by issue #5 ?

**Comment by richeyrobert** [comment]
Possibly, I split them out to separate issues because I wasn't sure if the new listener text bug was the same bug as the case insensitivity bug.

**Comment by ghost** [comment]
Makes sense, I will close this issue then.
